In [ ]:
# sklearn库的PCA分析法：
#https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

In [1]:
import numpy as np
from sklearn.decomposition import PCA
import pandas as pd

In [ ]:
matrix =[] #输入你的变量的矩阵

In [16]:

X = np.array(matrix)
print(X)
pca = PCA(n_components='mle')#设为'mle'：则自动选取component的数量
pca.fit(X)
#PCA(copy=True, n_components=2, whiten=False) 结果
print(pca.explained_variance_ratio_) 
#所得到的n个成分各自的方差百分比,这里可以理解为单个变量方差贡献率
print(pca.singular_values_)  
#所得到的新变量的系数
print(pca.n_components_)
n=pca.singular_values_
#如何组合
print(pca.components_ )
each=pca.components_ 


[[6.00000000e-01 8.00000000e-01 4.00000000e-01 0.00000000e+00]
 [4.00000000e-01 2.00000000e-01 1.00000000e+00 2.11413382e-04]
 [6.00000000e-01 2.00000000e-01 4.00000000e-01 1.61921683e-04]
 [4.00000000e-01 2.00000000e-01 8.00000000e-01 1.78928012e-04]
 [4.00000000e-01 2.00000000e-01 4.00000000e-01 3.19149505e-03]
 [6.00000000e-01 4.00000000e-01 6.00000000e-01 1.78162877e-04]
 [6.00000000e-01 4.00000000e-01 6.00000000e-01 2.89532405e-04]
 [4.00000000e-01 4.00000000e-01 4.00000000e-01 1.21551404e-04]
 [4.00000000e-01 6.00000000e-01 8.00000000e-01 6.65593644e-05]
 [4.00000000e-01 6.00000000e-01 4.00000000e-01 3.67506181e-04]
 [2.00000000e-01 6.00000000e-01 4.00000000e-01 3.02873213e-04]
 [4.00000000e-01 4.00000000e-01 6.00000000e-01 4.48029224e-04]
 [4.00000000e-01 2.00000000e-01 4.00000000e-01 7.68828519e-04]
 [4.00000000e-01 4.00000000e-01 6.00000000e-01 1.09767600e-03]
 [1.00000000e+00 1.00000000e+00 4.00000000e-01 8.05977819e-04]
 [4.00000000e-01 2.00000000e-01 8.00000000e-01 1.000000

In [66]:
coefficients=[]
for i in range(4):
    a=0
    for j in range(len(n)):
        a+=n[j]*each[j][i]
    coefficients.append(a)